# Generated by Django 3.2.4 on 2021-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middlename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
