# Generated by Django 3.2.4 on 2021-07-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210715_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastn_name',
            new_name='last_name',
        ),
    ]
