# Generated by Django 3.2.4 on 2021-07-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_related_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_image',
            field=models.ImageField(default='defaultimg.jpg', null=True, upload_to='images/'),
        ),
    ]
