# Generated by Django 3.2.4 on 2021-07-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profie_picture',
            field=models.ImageField(default='defaultimg.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='related_image',
            field=models.ImageField(default='defaultimg.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
