# Generated by Django 3.2.4 on 2021-07-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profie_picture',
            field=models.ImageField(blank=True, default='defaultimg.jpg', null=True, upload_to=''),
        ),
    ]
