# Generated by Django 3.2.4 on 2021-07-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profie_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='defaultimg.jpg', null=True, upload_to=''),
        ),
    ]
