# Generated by Django 3.2.4 on 2021-07-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blogpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='blog.jpg', null=True, upload_to=''),
        ),
    ]
