# Generated by Django 3.2.4 on 2021-07-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='categories',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='blog.UserProfile'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='related_image',
            field=models.ImageField(default='blog.jpg', null=True, upload_to='blog_images/'),
        ),
    ]
