# Generated by Django 3.2.4 on 2021-07-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210723_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='categories',
            new_name='category',
        ),
    ]
