# Generated by Django 3.2.4 on 2021-07-30 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(300), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
