# Generated by Django 3.2.4 on 2021-07-30 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(150), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
