# Generated by Django 4.0.2 on 2022-02-16 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210730_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(200), django.core.validators.MinLengthValidator(30)]),
        ),
    ]
